export const cityContent = {
    bangalore: {
        name: 'Bangalore',
        formalName: 'Bengaluru',
        title: 'Bike Rental in Bangalore | Self Drive Scooter & Bike on Rent | Zugo',
        description: 'Self-drive bike and scooter rental in Bangalore. Hourly, daily and weekly plans available. Book online instantly at zugo.co.in',
        seoDescription: 'Zugo offers affordable self-drive bike rental and scooty on rent in Bangalore (Bengaluru). Locations in Koramangala, Indiranagar, HSR Layout, Whitefield & more. Hourly, daily, weekly rentals available.',
        heroTitle: 'Rent Freedom in <span class="bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-purple-600">Bangalore</span>',
        heroSubtitle: 'Skip the traffic and explore the Garden City on your own terms. From Koramangala to Whitefield, we have you covered.',
        intro: 'Bangalore, the Silicon Valley of India, is best explored on two wheels. Whether you need to beat the notorious traffic or enjoy a weekend ride to Nandi Hills, Zugo provides the most flexible self-drive bike rental service in the city.',
        keywords: [
            'bike rental Bangalore',
            'scooty on rent Bangalore',
            'rent bike Bangalore',
            'two wheeler rental Bangalore',
            'bike rent Bangalore',
            'self drive bike Bangalore',
            'scooter rental Bangalore',
            'bike rental Bengaluru',
            'rentals in Bangalore',
            'bike on rent in Bangalore',
        ],
        coordinates: { latitude: 12.9716, longitude: 77.5946 },
        points: [
            { title: 'Beat the Traffic', desc: 'Zip through Bangalore traffic with ease on our well-maintained scooters and bikes.' },
            { title: 'Weekend Getaways', desc: 'Perfect for trips to Nandi Hills, Mysore, or Coorg.' },
            { title: 'Hubs Across City', desc: 'Pick up from Indiranagar, Koramangala, HSR Layout, and more.' }
        ],
        faq: [
            { q: 'Where can I pick up the bike in Bangalore?', a: 'We have pickup locations in Koramangala, Indiranagar, HSR Layout, Whitefield, and near Majestic and Cantonment Railway Stations.' },
            { q: 'Is fuel included in bike rental in Bangalore?', a: 'No, fuel is not included. You will start with a full tank and must return it with a full tank, or pay for the fuel used.' },
            { q: 'What is the cheapest bike rental in Bangalore?', a: 'Zugo offers bike and scooty rentals in Bangalore starting at just ₹20 per hour. Daily and monthly plans are also available at discounted rates.' },
            { q: 'Can I rent a bike in Bangalore without a deposit?', a: 'Yes, verified Zugo users can rent bikes with zero deposit. New users may need minimal documentation.' },
        ],
        areas: ['Koramangala', 'Indiranagar', 'Whitefield', 'HSR Layout', 'Electronic City', 'Marathahalli', 'Jayanagar', 'Hebbal']
    },
    delhi: {
        name: 'Delhi',
        formalName: 'New Delhi',
        title: 'Bike Rental in Delhi | Self Drive Two Wheeler on Rent | Zugo',
        description: 'Rent bikes and scooters in Delhi on self-drive. Hourly, daily and monthly plans. Verified vehicles, instant online booking at zugo.co.in',
        seoDescription: 'Zugo offers the best bike rental and scooty on rent service in Delhi NCR. Affordable self-drive two wheelers available near major Metro stations. Hourly, daily, and monthly plans.',
        heroTitle: 'Explore the Capital on <span class="bg-clip-text text-transparent bg-gradient-to-r from-orange-400 to-red-600">Two Wheels</span>',
        heroSubtitle: 'From the narrow lanes of Chandni Chowk to the wide avenues of Lutyens, experience Delhi like never before.',
        intro: 'Delhi, the heart of India, offers a mix of history and modernity. Renting a bike in Delhi gives you the freedom to explore monuments, markets, and food joints at your own pace without depending on public transport.',
        keywords: [
            'bike rental Delhi',
            'scooty on rent Delhi',
            'rent bike Delhi',
            'two wheeler rental Delhi',
            'bike rent Delhi',
            'self drive bike Delhi',
            'bike on rent in Delhi',
            'scooter rental Delhi NCR',
            'rentals in Delhi',
            'bike rental near me Delhi',
        ],
        coordinates: { latitude: 28.6139, longitude: 77.2090 },
        points: [
            { title: 'Metro Connectivity', desc: 'Pickup points near major Metro stations for last-mile connectivity.' },
            { title: 'Student Friendly', desc: 'Special discounts for students in North and South Campus.' },
            { title: 'Tour Ready', desc: 'Bikes available for trips to Agra, Jaipur, and Rishikesh.' }
        ],
        faq: [
            { q: 'Can I take the rented bike from Delhi to Ladakh?', a: 'For long trips like Ladakh, please check our specific heavy-duty cruiser section and read terms regarding interstate permits.' },
            { q: 'Do I need a helmet with bike rental in Delhi?', a: 'Yes, a helmet for the rider is mandatory and provided by us. Pillion helmets are also available on request.' },
            { q: 'What documents are needed for bike rental in Delhi?', a: 'You need a valid driving license and Aadhar card. The process is completely digital via the Zugo app.' },
        ],
        areas: ['Connaught Place', 'South Delhi', 'Dwarka', 'Karol Bagh', 'Laxmi Nagar', 'Rohini', 'Saket', 'Nehru Place']
    },
    gurugram: {
        name: 'Gurugram',
        formalName: 'Gurugram',
        title: 'Rent Bike in Gurugram | Self Drive Bike & Scooty Rentals Gurgaon | Zugo',
        description: 'Rent self-drive bikes and scooters in Gurugram (Gurgaon). Easy documentation, instant booking. Best for office commute and weekend rides. Affordable two wheeler on rent.',
        seoDescription: 'Zugo provides self-drive bike rental and scooty on rent in Gurugram (Gurgaon). Perfect for daily office commute. Pickup near Huda City Centre and Cyber City.',
        heroTitle: 'Ride Smart in <span class="bg-clip-text text-transparent bg-gradient-to-r from-yellow-400 to-orange-500">Cyber City</span>',
        heroSubtitle: 'Commute to your office or explore Cyber Hub without the hassle of cabs.',
        intro: 'Gurugram is a hub of corporate offices and glitzy malls. Avoid the surge pricing of cabs and rent a bike for your daily commute or evening outings.',
        keywords: [
            'bike rental Gurugram',
            'bike rental Gurgaon',
            'scooty on rent Gurgaon',
            'rent bike Gurugram',
            'two wheeler rental Gurugram',
            'bike rent Gurgaon',
            'self drive bike Gurgaon',
            'rentals in Gurugram',
            'bike on rent in Gurgaon',
        ],
        coordinates: { latitude: 28.4595, longitude: 77.0266 },
        points: [
            { title: 'Corporate Packages', desc: 'Monthly rental plans perfect for daily office commuters.' },
            { title: 'Metro Access', desc: 'Pickup near Huda City Centre and Cyber City Rapid Metro.' },
            { title: 'Night Life', desc: 'Safe and reliable rides for your late-night food runs to Sector 29.' }
        ],
        faq: [
            { q: 'Is there a security deposit for bike rental in Gurugram?', a: 'We have a low security deposit policy for verified users with clean driving records.' },
            { q: 'Can I extend my bike rental booking in Gurgaon?', a: 'Yes, you can extend your booking via the app subject to vehicle availability.' },
            { q: 'What bikes are available for rent in Gurugram?', a: 'We offer scooters like Honda Activa, bikes like Pulsar, Royal Enfield, and more. Check the Zugo app for real-time availability.' },
        ],
        areas: ['Cyber City', 'Sector 29', 'MG Road', 'Sohna Road', 'Udyog Vihar', 'Golf Course Road', 'DLF Phase 3']
    },
    rishikesh: {
        name: 'Rishikesh',
        formalName: 'Rishikesh',
        title: 'Bike Rental in Rishikesh | Royal Enfield, Scooter & Activa | Zugo',
        description: 'Rent bikes & scooters in Rishikesh from Rs 300/day. Royal Enfield, Activa, Dominar & more. Pickup at Laxman Jhula, Tapovan, Bus Stand. Instant booking. No hidden charges.',
        seoDescription: 'Zugo is the best bike rental and scooty on rent service in Rishikesh, Uttarakhand. Rent two wheelers to explore Laxman Jhula, Tapovan, Neelkanth Mahadev Temple, and more. Affordable hourly, daily & weekly rental plans.',
        heroTitle: 'Bike Rental in <span class="bg-clip-text text-transparent bg-gradient-to-r from-emerald-400 to-teal-500">Rishikesh</span>',
        heroSubtitle: 'Book Royal Enfield, Activa, scooters and bikes in Rishikesh with pickup near Tapovan, Laxman Jhula, Ram Jhula and the Bus Stand.',
        intro: 'Rishikesh is easiest to explore on two wheels. From Tapovan cafes and Laxman Jhula lanes to rides towards Neelkanth, Shivpuri and the Ganga ghats, Zugo helps travellers book verified bikes and scooters quickly without hidden charges. Choose from Activa, Royal Enfield, Dominar and more with flexible daily rentals.',
        keywords: [
            'bike rental Rishikesh',
            'scooty on rent in Rishikesh',
            'rent bike Rishikesh',
            'two wheeler rental Rishikesh',
            'bike rent Rishikesh',
            'rentals in Rishikesh',
            'scooter rental Rishikesh',
            'bike on rent in Rishikesh',
            'self drive bike Rishikesh',
            'scooty rental Rishikesh',
            'vehicle rental Rishikesh',
            'cheap bike rental Rishikesh',
            'bike hire Rishikesh',
        ],
        coordinates: { latitude: 30.0869, longitude: 78.2676 },
        points: [
            { title: 'Mountain Ready', desc: 'Powerful bikes suitable for steep mountain roads and curvy hill routes.' },
            { title: 'Temple Run', desc: 'Easy access to Neelkanth Mahadev, Beatles Ashram, Ram Jhula, and Ghats.' },
            { title: 'Flexible Hours', desc: 'Hourly rentals available for short trips. Daily and weekly plans for longer stays.' }
        ],
        faq: [
            { q: 'What is the price of bike rental in Rishikesh?', a: 'Bike and scooty rentals in Rishikesh start from Rs 300 per day. Royal Enfield rentals start from Rs 800 per day. Check zugo.co.in for exact pricing.' },
            { q: 'Where can I pick up a rental bike in Rishikesh?', a: 'Zugo has pickup points near Tapovan, Laxman Jhula, Ram Jhula, and the Rishikesh Bus Stand.' },
            { q: 'Do I need a driving licence to rent a bike in Rishikesh?', a: 'Yes, a valid two-wheeler driving licence is required to rent a bike through Zugo in Rishikesh.' },
            { q: 'Can I rent a Royal Enfield in Rishikesh?', a: 'Yes, Zugo offers Royal Enfield Classic 350, Bullet 350, and Himalayan for rent in Rishikesh starting from Rs 800 per day.' },
            { q: 'Is a deposit required to rent a bike in Rishikesh?', a: 'Verified Zugo users can rent with zero deposit. New users pay a small refundable security deposit.' },
        ],
        areas: ['Tapovan', 'Laxman Jhula', 'Ram Jhula', 'Main Market', 'Shivpuri', 'Neelkanth Road', 'Badrinath Highway', 'Bus Stand']
    }
};
